### ISSUE TITLE
Additional properties are not allowed 

### ISSUE THREAD

**Issue by jvdborre** [singer-io/tap-jira#29]
Hi everyone,

When including the Projects scheme in a catalog file generated by the discovery option, I get the following return message:

CRITICAL Record does not pass schema validation: Additional properties are not allowed ('style', 'isPrivate' were unexpected)

Has someone else seen this before?

**Comment by timvisher** [comment]
I'd need to know more about the version you're running but I would say this is unexpected. In 47dff958e84074fa1c8d1e01aab8f184c87170d7 we explicitly set `additionalProperties` to `true` wherever it had been set to `false` and that was back on 2018-08-31. Is it possible you're running an older version?

FWIW, we should actually probably delete all the `"additionalProperties": true` entries in the schema files as we should never be setting that property at all. `true` is its default value.

If you wanted to make a PR to that effect you could probably do something like the following:

```
for f in tap_jira/schemas/!(*.new).json
do
    jq 'walk(if type == "object" then del(.additionalProperties) else . end)' "$f" > "${f%.json}.new.json"
done
```

**Comment by timvisher** [comment]
This should be fixed in https://github.com/singer-io/tap-jira/commit/3dae6f3748078b7e9a79cbc62235d5ae43bc5630
